export const LegalNotice = {
  de: {
    TITLE: 'Impressum',
    SUBTITLE: 'Rechtliche Hinweise',
    STUDENT_LIST: '[Liste der Studierenden]',
    ADDRESS: '[Adresse des JOIN-Betreibers - z.B. einer der Studierenden]',
    POSTCODE_CITY: '[PLZ und Stadt]',
    EXPLORING_BOARD_TITLE: 'Erkundung des Boards',
    EXPLORING_BOARD_TEXT: 'Email: oliverplit@gmail.com',
    ACCEPTANCE_TITLE: 'Akzeptanz der Bedingungen',
    ACCEPTANCE_TEXT: 'Durch den Zugriff und die Nutzung von Portfolio erkennen Sie die folgenden Bedingungen an...',
    SCOPE_TITLE: 'Geltungsbereich und Eigentum',
    SCOPE_TEXT: 'Portfolio wurde als Teil eines studentischen Gruppenprojekts entwickelt...',
    PROPRIETARY_TITLE: 'Eigentumsrechte',
    PROPRIETARY_TEXT: 'Abgesehen vom Design der Developer Akademie GmbH behalten wir, die Studierenden, alle Eigentumsrechte...',
    USAGE_TITLE: 'Nutzung des Produkts',
    USAGE_TEXT: 'Portfolio darf nur für rechtmäßige Zwecke verwendet werden...',
    DISCLAIMER_TITLE: 'Haftungsausschluss',
    DISCLAIMER_TEXT: 'Portfolio wird "wie besehen" bereitgestellt, ohne Garantie...',
    INDEMNITY_TITLE: 'Entschädigung',
    INDEMNITY_TEXT: 'Sie erklären sich damit einverstanden, uns, die Developer Akademie...',
    CONTACT_EMAIL: 'Für Fragen kontaktieren Sie uns unter [Kontakt Email].',
    DATE: 'Datum: 26. Juli 2025'
  },
  en: {
    TITLE: 'Legal Notice',
    SUBTITLE: 'Imprint',
    STUDENT_LIST: '[Student Names List]',
    ADDRESS: '[Address of the JOIN operator - e.g. one of the students]',
    POSTCODE_CITY: '[Postcode and city]',
    EXPLORING_BOARD_TITLE: 'Exploring the Board',
    EXPLORING_BOARD_TEXT: 'Email: oliverplit@gmail.com',
    ACCEPTANCE_TITLE: 'Acceptance of terms',
    ACCEPTANCE_TEXT: 'By accessing and using Portfolio, you acknowledge the following terms...',
    SCOPE_TITLE: 'Scope and ownership of the product',
    SCOPE_TEXT: 'Portfolio has been developed as part of a student group project...',
    PROPRIETARY_TITLE: 'Proprietary rights',
    PROPRIETARY_TEXT: 'Aside from the design owned by Developer Akademie GmbH, we, the listed students, retain all proprietary rights...',
    USAGE_TITLE: 'Use of the product',
    USAGE_TEXT: 'Portfolio is intended to be used for lawful purposes only...',
    DISCLAIMER_TITLE: 'Disclaimer of warranties and limitation of liability',
    DISCLAIMER_TEXT: 'Portfolio is provided "as is" without warranty of any kind...',
    INDEMNITY_TITLE: 'Indemnity',
    INDEMNITY_TEXT: 'You agree to indemnify, defend and hold harmless us...',
    CONTACT_EMAIL: 'For any questions or notices, please contact us at oliverplit2005@gmail.com.',
    DATE: 'Date: July 26, 2025'
  }
};
